#!/usr/bin/env python3
"""
Convert a WAV file to 16-bit PCM mono at 16 kHz.

This tool can generate:
1) raw PCM file (.pcm / .raw)
2) C header with an int16 array compatible with rp/src/a2dp.c

Examples:
  python3 tools/wav_to_pcm16_mono.py input.wav \
    --raw-output /tmp/sample.pcm \
    --header-output rp/src/include/a2dp_pcm_sample.h

  python3 tools/wav_to_pcm16_mono.py input.wav --header-output sample.h
"""

from __future__ import annotations

import argparse
import pathlib
import struct
import sys
import wave


def _decode_sample_to_float(data: bytes, sample_width: int) -> float:
    if sample_width == 1:
        # 8-bit PCM is unsigned in WAV.
        return (data[0] - 128) / 128.0

    if sample_width == 2:
        value = int.from_bytes(data, byteorder="little", signed=True)
        return value / 32768.0

    if sample_width == 3:
        value = int.from_bytes(data, byteorder="little", signed=False)
        if value & 0x800000:
            value -= 1 << 24
        return value / 8388608.0

    if sample_width == 4:
        value = int.from_bytes(data, byteorder="little", signed=True)
        return value / 2147483648.0

    raise ValueError(f"Unsupported sample width: {sample_width} bytes")


def _read_wav_as_mono_float(
    wav_path: pathlib.Path,
) -> tuple[list[float], int, int]:
    with wave.open(str(wav_path), "rb") as wav_file:
        if wav_file.getcomptype() != "NONE":
            raise ValueError(
                f"Compressed WAV is not supported: {wav_file.getcomptype()}"
            )

        channels = wav_file.getnchannels()
        sample_width = wav_file.getsampwidth()
        sample_rate = wav_file.getframerate()
        frame_count = wav_file.getnframes()
        raw_frames = wav_file.readframes(frame_count)

    if channels <= 0:
        raise ValueError("Invalid WAV: zero channels")

    frame_size = channels * sample_width
    if frame_size <= 0 or (len(raw_frames) % frame_size) != 0:
        raise ValueError("Invalid WAV: inconsistent frame data size")

    mono_samples: list[float] = []
    offset = 0
    total_frames = len(raw_frames) // frame_size
    for _ in range(total_frames):
        mixed = 0.0
        for channel in range(channels):
            start = offset + (channel * sample_width)
            end = start + sample_width
            mixed += _decode_sample_to_float(raw_frames[start:end], sample_width)
        mono_samples.append(mixed / channels)
        offset += frame_size

    return mono_samples, sample_rate, channels


def _resample_linear(samples: list[float], src_rate: int, dst_rate: int) -> list[float]:
    if not samples:
        return []
    if src_rate == dst_rate:
        return list(samples)

    out_len = max(1, int(round(len(samples) * (dst_rate / src_rate))))
    out: list[float] = []
    step = src_rate / dst_rate

    for i in range(out_len):
        pos = i * step
        left = int(pos)
        if left >= len(samples) - 1:
            out.append(samples[-1])
            continue

        frac = pos - left
        right = left + 1
        out_sample = samples[left] + ((samples[right] - samples[left]) * frac)
        out.append(out_sample)

    return out


def _float_to_int16(samples: list[float]) -> list[int]:
    out: list[int] = []
    for sample in samples:
        if sample >= 1.0:
            value = 32767
        elif sample <= -1.0:
            value = -32768
        else:
            value = int(round(sample * 32767.0))
        out.append(value)
    return out


def _write_raw_pcm(samples: list[int], out_path: pathlib.Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("wb") as output:
        if samples:
            output.write(struct.pack(f"<{len(samples)}h", *samples))


def _header_guard_from_path(path: pathlib.Path) -> str:
    guard = path.name.upper()
    for char in ".-/\\ ":
        guard = guard.replace(char, "_")
    return f"{guard}_"


def _write_c_header(
    samples: list[int],
    out_path: pathlib.Path,
    symbol: str,
    count_symbol: str,
    target_rate: int,
) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    guard = _header_guard_from_path(out_path)

    with out_path.open("w", encoding="utf-8", newline="\n") as output:
        output.write("/* Auto-generated by tools/wav_to_pcm16_mono.py */\n")
        output.write(f"#ifndef {guard}\n")
        output.write(f"#define {guard}\n\n")
        output.write("#include <stdint.h>\n\n")
        output.write(f"#define A2DP_PCM_SAMPLE_RATE_HZ {target_rate}u\n")
        output.write("#define A2DP_PCM_SAMPLE_CHANNELS 1u\n\n")
        output.write(f"static const int16_t {symbol}[] = {{\n")

        values_per_line = 12
        for start in range(0, len(samples), values_per_line):
            row = samples[start : start + values_per_line]
            row_text = ", ".join(str(value) for value in row)
            output.write(f"    {row_text},\n")

        output.write("};\n\n")
        output.write(
            f"static const uint32_t {count_symbol} = "
            f"(uint32_t)(sizeof({symbol}) / sizeof({symbol}[0]));\n\n"
        )
        output.write(f"#endif  // {guard}\n")


def _default_raw_output(input_wav: pathlib.Path) -> pathlib.Path:
    return input_wav.with_suffix(".pcm")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert WAV to raw PCM 16-bit mono and optional C header."
    )
    parser.add_argument("input_wav", type=pathlib.Path, help="Input WAV file")
    parser.add_argument(
        "--raw-output",
        type=pathlib.Path,
        default=None,
        help="Output raw PCM path (default: input basename with .pcm)",
    )
    parser.add_argument(
        "--header-output",
        type=pathlib.Path,
        default=None,
        help="Optional C header output path",
    )
    parser.add_argument(
        "--target-rate",
        type=int,
        default=16000,
        help="Target sample rate in Hz (default: 16000)",
    )
    parser.add_argument(
        "--symbol",
        type=str,
        default="a2dp_pcm_sample_data",
        help="C array symbol name for header output",
    )
    parser.add_argument(
        "--count-symbol",
        type=str,
        default="a2dp_pcm_sample_count",
        help="C count symbol name for header output",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_wav: pathlib.Path = args.input_wav
    raw_output: pathlib.Path = args.raw_output or _default_raw_output(input_wav)
    header_output: pathlib.Path | None = args.header_output

    if args.target_rate <= 0:
        print("error: --target-rate must be > 0", file=sys.stderr)
        return 1

    if not input_wav.exists():
        print(f"error: input WAV not found: {input_wav}", file=sys.stderr)
        return 1

    try:
        mono_float, src_rate, src_channels = _read_wav_as_mono_float(input_wav)
        resampled = _resample_linear(mono_float, src_rate, args.target_rate)
        pcm16 = _float_to_int16(resampled)

        _write_raw_pcm(pcm16, raw_output)
        if header_output is not None:
            _write_c_header(
                pcm16,
                header_output,
                args.symbol,
                args.count_symbol,
                args.target_rate,
            )
    except Exception as exc:  # pragma: no cover - CLI error path
        print(f"error: {exc}", file=sys.stderr)
        return 1

    duration_ms = 0.0
    if args.target_rate > 0:
        duration_ms = (len(pcm16) * 1000.0) / args.target_rate

    print(f"Input:        {input_wav}")
    print(f"Source:       {src_rate} Hz, {src_channels} channel(s)")
    print(f"Target:       {args.target_rate} Hz, mono, 16-bit")
    print(f"Samples:      {len(pcm16)} ({duration_ms:.1f} ms)")
    print(f"Raw output:   {raw_output}")
    if header_output is not None:
        print(f"Header output:{header_output}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
